### ISSUE TITLE
Request for explanation of how to run the code

### ISSUE THREAD

**Issue by jiajunxin** [caulk-crypto/caulk#3]
Could you please provide a more detailed explanation of how to run the code, especially for the pre-computation part of the paper?
I suppose the pre-computation time in the code is "Time to compute all KZG openings" by running single_opening.rs.
But I did not see any place that can use the precomputed SRS data.

**Comment by khovratovich** [comment]
The precomputation part is not callable per se, but for every run we check if we can load the precomputation from file, and if not we generate the openings and then store it.

https://github.com/caulk-crypto/caulk/blob/main/src/multi/mod.rs#L705-L730

**Comment by jiajunxin** [comment]
Yes, I do see this part for multi-openings. How about for the single opening?

**Comment by khovratovich** [comment]
I think we did not implement it for the single.

**Comment by jiajunxin** [comment]
If I run the single opening with the following operations, am I getting the result in Table 4 in the paper?

What is the bitsize of the degree of the polynomial inside the commitment?
16
Time to setup single openings of table size 65536 = 66.2134808s
Time to KZG commit one element from table size 65536 = 11.3296164s
Which position in the vector should we open at?
1
Should we open all possible positions? Opening all possible positions is slow.  Please input either YES or NO
YES
Time to compute all KZG openings 6590.5532914s

**Comment by jiajunxin** [comment]
I changed the test machine with better performance and get similar results in the paper! Thanks for the help.
